### PR TITLE
Fix selection error in graphs

### LINKED ISSUE #126: [BUG] Selection error in the graph
En el gráfico de evaluación de fallecidos por días hay un error cuando se intenta seleccionar el último punto de la gráfica. Cuando intentas seleccionar ese punto lo que hace es ubicarse en cualquier otro punto del gráfico..
Android 8

### PR DESCRIPTION
**Pull request by georkings**
fixes #126 passing a List of multidimensional elements to charts data instead of a List of unidimensional elements.
it also improves some identation in evolution_cases_widget.dart and curves_evolution.dart

### CODE REVIEW

File: lib/src/widgets/curves_evolution.dart [hunk 1]
```diff
@@ -118,37 +119,43 @@ class CurvesEvolutionWidgetState extends State<CurvesEvolutionWidget> {
...
+                  List<double>.from(value['cummulative_sum']),
+                ]).toList(),
+                domainLowerBoundFn: (_, __) => 1.4771212547196624,
+              );
+            }).toList() +
+            [
+              charts.Series<List, double>(
+                id: 'Cuba',
+                colorFn: (_, __) => colors[index],
+                domainFn: (_, i) =>
```
Comment (leynier) [inline lib/src/widgets/curves_evolution.dart:149]: Use `domainFn: (item, _) =>item[1],

Comment (leynier) [inline lib/src/widgets/curves_evolution.dart:149]:
```suggestion
                domainFn: (item, _) => item[1],
```

**Comment by georkings** [comment]
> Thank you very much!!!

My pleasure!
